### PR TITLE
Use latest release of panc

### PR DESCRIPTION
**Pull request by jrha**
@jouvin & @stdweird this should fix the problem seen in https://github.com/quattor/template-library-core/pull/173

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha that variable is unused in the script.

**Comment by jrha** [comment]
*sigh*

**Comment by jrha** [comment]
Actually I believe it is used in this piece of magic https://github.com/quattor/scdb/blob/dd89b18803e05f296c895186fc2c724823b61f03/utils/scdb/create-vanilla-SCDB.sh#L209-L215

**Comment by jouvin** [comment]
I think I know what has to be done... just need a few minutes to do it... Hopefully soon!

**Comment by jouvin** [comment]
Missing external in Quattor legacy SVN repo fixed. We may need to fix at an alternative to easily get all SCDB pieces from the script...

**Pull request merged**
